### PR TITLE
Enable CI, fix on 32 bit

### PR DESCRIPTION
**Pull request by tkelman**
Please enable Travis and AppVeyor here, as long as there are still important packages that haven't migrated to the replacement.

### CODE REVIEW

**Comment by tkelman** [comment]
thanks

**Comment by ssfrr** [comment]
Thanks for fixing the 32-bit thing, sorry about that.

**Comment by tkelman** [comment]
This is why we turn tests on.

**Comment by tkelman** [comment]
Bump. Please enable Travis and AppVeyor if you can.

**Pull request merged**
