### PR TITLE
Update for 0.4 deprecations: pointer conversions, int(x), etc

### PR DESCRIPTION
**Pull request by timholy**
I didn't fix everything; in particular, I left the `UInt` type names lowercase.

### CODE REVIEW

**Comment by timholy** [comment]
(But these I could do without requiring `Compat`.)

**Comment by timholy** [comment]
This may also fix #16.

It would be great to get this merged and a new release tagged; it's causing Travis timeouts for packages like ImageView.jl (which relies on TestImages.jl which relies on this). It's taking more than 10 minutes to unpack a file that takes only a few seconds on 0.3, because deprecation warnings just kill performance.

**Comment by timholy** [comment]
Images.jl too: https://travis-ci.org/timholy/Images.jl/jobs/57105231

**Comment by tkelman** [comment]
Sorry for the sort of unrelated question, but do we know why deprecation warnings are so insanely slow?

**Comment by timholy** [comment]
Thanks, @dcjones!

@tkelman, yes we do. The reason is the "warn once per source line" behavior, which means every deprecation involves taking a backtrace and comparing it against a stored record of which lines have issued deprecations previously. It's very nice behavior for someone who intends to fix the deprecation, but it certainly makes it slower.

**Comment by tkelman** [comment]
Thanks, I guess that makes sense, but I've seen it makes things unusably slow in a lot of cases. I guess that's why we have the `--depwarn=no` flag now.

**Pull request merged**
