### PR TITLE
Support for precompilation with version check

### PR DESCRIPTION
**Pull request by mdpradeep**

### CODE REVIEW

**Comment by mdpradeep** [comment]
@ViralBShah

**Comment by ViralBShah** [comment]
Would be great to merge this and tag a new version. Came up in the precompilation of AWS.jl, and will certainly help in many other places.

**Comment by ViralBShah** [comment]
Bump @dcjones @tkelman

**Comment by tkelman** [comment]
I don't have commit access here. Would love to see Travis turned on though, so we can see whether or not the package is precompile-safe. If we don't see any signs of @dcjones for, dunno, a week? we could consider temporarily redirecting Metadata to the mirror at https://github.com/JuliaPackageMirrors/Zlib.jl which can be more actively maintained.

**Comment by tkelman** [comment]
Have you checked that the package passes `Pkg.test("Zlib")` after making this change?

**Comment by mdpradeep** [comment]
Yes, I checked it on Mac & Ubuntu and it was fine. I will ask @bmharsha to test the same on Windows as well.

Regards,
Pradeep

**Comment by tkelman** [comment]
Okay great. In the absence of the package's author (I hope he's okay?) we may need to change the Package URL in Metadata to point to the mirror for a little while.

**Comment by bmharsha** [comment]
I tested this version on Windows using the default test file provided within the package, all tests passed without any issues.

**Comment by samoconnor** [comment]
bump

**Pull request merged**
